spring:
  application:
    name: spring-ai-rag-wallet-assistant

  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3.2
    chat:
      client:
        enabled: true  # ✅ Needed to auto-configure ChatClient
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: fri-20-jun-2025

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme

# Kibana credentials (optional – used only if your app integrates with Kibana)
kibana:
  username: kibana_system
  password: changeme
