filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.json
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5000"]

setup.kibana:
  host: "kibana:5601"

logging.level: info
